// <auto-generated />
namespace QuanLySinhVien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class SinhVienDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SinhVienDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201912050858367_SinhVienDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
